from typing import Any, Callable, TypeVar, overload

F = TypeVar("F", bound=Callable[..., Any])

def visible(func: F) -> F: ...
def chat(func: F) -> F: ...
def preflight(func: F) -> F: ...
def public(func: F) -> F: ...
def session(func: F) -> F: ...
def game(func: F) -> F: ...
def app(func: F) -> F: ...
def index(func: F) -> F: ...
def copy(func: F) -> F: ...
def dynamic(func: F) -> F: ...
def exclude(func: F) -> F: ...
def tick(func: F) -> F: ...

@overload
def text(func: F) -> F: ...
@overload
def text(content_type: str | None = None) -> Callable[[F], F]: ...
def protected(auth_function: str) -> Callable[[F], F]: ...
def location(name: str) -> Callable[[F], F]: ...
def button(label: str) -> Callable[[F], F]: ...
def price(pricePerCall: float, pricePerSec: float) -> Callable[[F], F]: ...
