# Dynamic tool: cube
# Description: Cube a number
# Generated by MCP Dynamic Function Server

def cube_number(number):
    """Cube a number."""
    return number * number * number

"""
Input schema:
{
  "type": "object",
  "properties": {
    "number": {
      "type": "number"
    }
  },
  "required": [
    "number"
  ]
}
"""
