# Dynamic tool: cube
# Description: Cube a number
# Generated by MCP Dynamic Function Server

def cube_number(args):
    """Cube a number."""
    number = args.get("number", 0)
    return number * number * number

"""
Input schema:
{
  "type": "object",
  "properties": {
    "number": {
      "type": "number"
    }
  },
  "required": [
    "number"
  ]
}
"""
