# Dynamic function: greet
# Description: A dynamically registered greeting function
# Generated by MCP Dynamic Function Server

def greet(name: str, times: int = 1) -> str:
    """Greets a person multiple times."""
    greetings = []
    for _ in range(times):
        greetings.append(f'Hello, {name}!')
    return ' '.join(greetings)

"""
Input schema:
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "times": {
      "type": "integer",
      "default": 1
    }
  },
  "required": [
    "name"
  ]
}
"""
