# Dynamic tool: add
# Description: Add two numbers together
# Generated by MCP Dynamic Function Server

def add(a, b):
    """Add two numbers together."""
    return a + b

"""
Input schema:
{
  "type": "object",
  "properties": {
    "a": {
      "type": "number"
    },
    "b": {
      "type": "number"
    }
  },
  "required": [
    "a",
    "b"
  ]
}
"""
