# Dynamic tool: square
# Description: Square a number
# Generated by MCP Dynamic Function Server

def square_number(number):
    """Square a number."""
    return number * number

"""
Input schema:
{
  "type": "object",
  "properties": {
    "number": {
      "type": "number"
    }
  },
  "required": [
    "number"
  ]
}
"""
